repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0-1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: debug-statements
  - id: name-tests-test
    args: ['--django']
  - id: detect-private-key
  - id: flake8

- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.2.0
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.1.1
  hooks:
  - id: pylint
    args: [
      '--verbose',
      '--disable',
      'E0401'
    ]
